import Foundation

/// Codable schema for `Resources/ModelManifest.json`.
///
/// The manifest pins both Hugging Face repos to **immutable commit SHAs**
/// (never a moving branch) and records the SHA256 of every file. App runtime
/// downloads validate each file against these hashes. The manifest is
/// generated by `scripts/generate_manifest.py` after a real download —
/// hashes are measured, never guessed.
struct ModelManifest: Codable, Sendable, Equatable {
    struct ModelInfo: Codable, Sendable, Equatable {
        let id: String
        let name: String
        let revision: String
        let language: String
        let license: String
        let upstreamRepo: String
    }

    struct BackendInfo: Codable, Sendable, Equatable {
        let id: String
        let kind: ASRBackendKind
        let repo: String
        /// Immutable commit SHA of the pinned HF revision.
        let revision: String
        /// Files, in download order. `path` is relative to the backend
        /// install directory.
        let files: [FileInfo]
        let totalDownloadBytes: Int
        /// Expected on-disk size after install (same as download for these
        /// repos; Core ML additionally needs the compiled cache).
        let installedBytes: Int
        /// Extra temp space the installer must keep free while working
        /// (partial files, staging copies, Core ML compilation).
        let stagingBytes: Int
        /// Minimum free disk space required before install begins.
        let minimumFreeDiskBytes: Int
        let license: String
        /// Core ML only: bump to invalidate every compiled `.mlmodelc`
        /// cache after a runtime/SDK contract change.
        var coreMLCompiledCacheVersion: Int?

        struct FileInfo: Codable, Sendable, Equatable {
            let path: String
            let url: String
            let bytes: Int
            let sha256: String
        }
    }

    struct RuntimeInfo: Codable, Sendable, Equatable {
        let sherpaOnnxVersion: String
        let sileroVAD: VadModelInfo

        struct VadModelInfo: Codable, Sendable, Equatable {
            let url: String
            let bytes: Int
            let sha256: String
        }
    }

    let schemaVersion: Int
    let model: ModelInfo
    let backends: [String: BackendInfo]
    let runtime: RuntimeInfo

    func backend(_ kind: ASRBackendKind) -> BackendInfo? {
        backends[kind.manifestKey]
    }

    static func load(bundle: Bundle = .main) throws -> ModelManifest {
        guard let url = bundle.url(forResource: "ModelManifest", withExtension: "json") else {
            throw ASREngineError.loadFailed(.coreMLFP16, underlying: "ModelManifest.json missing from bundle")
        }
        let data = try Data(contentsOf: url)
        do {
            return try JSONDecoder().decode(ModelManifest.self, from: data)
        } catch {
            throw ASREngineError.loadFailed(.coreMLFP16, underlying: "ModelManifest.json is invalid: \(error)")
        }
    }
}

extension ASRBackendKind {
    /// Key used in the manifest's `backends` dictionary.
    var manifestKey: String {
        switch self {
        case .coreMLFP16: return "coreml-fp16"
        case .sherpaONNXInt8: return "sherpa-onnx-int8"
        }
    }
}

/// Canonical on-disk locations for model files.
///
/// Layout (under Application Support):
/// ```
/// Models/
///   gigaam-v3-e2e-rnnt/
///     coreml-fp16/
///       Source/{*.mlpackage}
///       Metadata/{tokens.json, tokenizer.model, ...}
///       Compiled/{*.mlmodelc}
///     sherpa-onnx-int8/{encoder.int8.onnx, decoder.onnx, joiner.onnx, tokens.txt}
///   vad/silero_vad.onnx
/// ```
enum ModelPaths {
    static func modelsRoot() throws -> URL {
        let support = try FileManager.default.url(
            for: .applicationSupportDirectory, in: .userDomainMask,
            appropriateFor: nil, create: true
        )
        return support.appendingPathComponent("Models", isDirectory: true)
    }

    static func modelRoot() throws -> URL {
        try modelsRoot().appendingPathComponent("gigaam-v3-e2e-rnnt", isDirectory: true)
    }

    static func backendRoot(_ kind: ASRBackendKind) throws -> URL {
        try modelRoot().appendingPathComponent(kind.manifestKey, isDirectory: true)
    }

    /// Core ML source `.mlpackage` roots (uncompiled).
    static func coreMLSourceRoot() throws -> URL {
        try backendRoot(.coreMLFP16).appendingPathComponent("Source", isDirectory: true)
    }

    static func coreMLMetadataRoot() throws -> URL {
        try backendRoot(.coreMLFP16).appendingPathComponent("Metadata", isDirectory: true)
    }

    static func coreMLCompiledRoot() throws -> URL {
        try backendRoot(.coreMLFP16).appendingPathComponent("Compiled", isDirectory: true)
    }

    static func coreMLCompiledRoot(cacheVersion: Int) throws -> URL {
        try coreMLCompiledRoot()
            .appendingPathComponent("v\(cacheVersion)", isDirectory: true)
    }

    static func vadModelURL() throws -> URL {
        try modelsRoot().appendingPathComponent("vad", isDirectory: true)
            .appendingPathComponent("silero_vad.onnx")
    }
}
