import XCTest
@testable import LiveTranslateIOS

/// Shared support for model-dependent integration tests.
///
/// These tests run in the **separate integration test plan** (never normal
/// CI) and need real model files inside the host app's sandbox. Two ways to
/// get them there:
///
/// 1. They are already installed (e.g. an earlier run, or a manual copy).
/// 2. The `LIVETRANSLATE_MODELS_DIR` environment variable points at the
///    git-ignored `LocalModels/` directory produced by
///    `scripts/prepare_models.sh` — the helper copies the tree into the
///    sandbox before the first test runs.
///
/// If neither holds, every model-dependent test skips with instructions
/// rather than failing: a missing 446 MB download is not a code defect.
enum IntegrationModels {
    static let modelsDirEnvKey = "LIVETRANSLATE_MODELS_DIR"

    /// True when the given backend's files are present and hash-verified
    /// in the sandbox.
    static func isInstalled(_ kind: ASRBackendKind) async -> Bool {
        guard let manifest = try? ModelManifest.load(),
              let info = manifest.backend(kind),
              let root = try? ModelPaths.backendRoot(kind) else { return false }
        return await ModelIntegrityVerifier.verifyBackend(info, root: root) == nil
    }

    /// Ensure the backend's model files are present, copying from
    /// `LIVETRANSLATE_MODELS_DIR` if needed. Skips the test when they
    /// cannot be made available.
    static func requireInstalled(_ kind: ASRBackendKind) async throws {
        if await isInstalled(kind) { return }

        guard let source = ProcessInfo.processInfo.environment[modelsDirEnvKey],
              !source.isEmpty else {
            throw XCTSkip("""
                \(kind.displayName) is not installed in the app sandbox and \
                \(modelsDirEnvKey) is not set. Run scripts/prepare_models.sh \
                once, then run the integration scheme with \
                \(modelsDirEnvKey)=$PWD/LocalModels.
                """)
        }
        let sourceRoot = URL(fileURLWithPath: source)
        let fm = FileManager.default
        guard fm.fileExists(atPath: sourceRoot.path) else {
            throw XCTSkip("\(modelsDirEnvKey)=\(source) does not exist.")
        }
        do {
            try copyModels(from: sourceRoot)
        } catch {
            XCTFail("Copying models from \(source) failed: \(error)")
            return
        }
        let verified = await isInstalled(kind)
        XCTAssertTrue(verified,
                      "\(kind.displayName) still not verifiable after copying from \(source)")
    }

    /// Copy the `LocalModels/` layout into the sandbox layout expected by
    /// `ModelPaths` (Models/gigaam-v3-e2e-rnnt/… and Models/vad/…).
    static func copyModels(from sourceRoot: URL) throws {
        let fm = FileManager.default
        let modelRoot = try ModelPaths.modelRoot()

        try copyTree(
            from: sourceRoot.appendingPathComponent("coreml-fp16"),
            to: modelRoot.appendingPathComponent("coreml-fp16", isDirectory: true)
        )
        try copyTree(
            from: sourceRoot.appendingPathComponent("sherpa-onnx-int8"),
            to: modelRoot.appendingPathComponent("sherpa-onnx-int8", isDirectory: true)
        )

        let vadSource = sourceRoot.appendingPathComponent("silero_vad.onnx")
        if fm.fileExists(atPath: vadSource.path) {
            let vadDest = try ModelPaths.vadModelURL()
            try fm.createDirectory(at: vadDest.deletingLastPathComponent(),
                                   withIntermediateDirectories: true)
            if fm.fileExists(atPath: vadDest.path) {
                try fm.removeItem(at: vadDest)
            }
            try fm.copyItem(at: vadSource, to: vadDest)
        }
    }

    private static func copyTree(from source: URL, to destination: URL) throws {
        let fm = FileManager.default
        guard fm.fileExists(atPath: source.path) else { return }
        if fm.fileExists(atPath: destination.path) {
            try fm.removeItem(at: destination)
        }
        try fm.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try fm.copyItem(at: source, to: destination)
    }
}

/// Fixture loading for the Russian speech samples generated by
/// `scripts/generate_coreml_golden_fixtures.py`, including the PyTorch
/// reference transcripts recorded in the `.meta.json` files.
enum IntegrationFixtures {
    struct Fixture {
        let name: String
        let samples: [Float]
        let referenceText: String
        var duration: TimeInterval { TimeInterval(samples.count) / 16_000 }
    }

    static func load(named name: String) throws -> Fixture {
        let bundle = Bundle(for: BundleToken.self)
        func resource(_ ext: String) throws -> URL {
            if let url = bundle.url(forResource: name, withExtension: ext, subdirectory: "Fixtures") {
                return url
            }
            guard let url = bundle.url(forResource: name, withExtension: ext) else {
                throw XCTSkip("fixture \(name).\(ext) is not part of the integration test resources")
            }
            return url
        }

        struct Meta: Decodable {
            struct PyTorch: Decodable { let text: String }
            let pytorch: PyTorch
        }
        let meta = try JSONDecoder().decode(Meta.self, from: Data(contentsOf: try resource("meta.json")))
        let samples = try TestWAVReader.readMono16kSamples(at: try resource("wav"))
        return Fixture(name: name, samples: samples, referenceText: meta.pytorch.text)
    }
}

private final class BundleToken {}

/// Minimal RIFF/WAV reader for the fixture format (16-bit PCM, mono, 16 kHz),
/// identical to the unit-test target's reader.
enum TestWAVReader {
    enum ReaderError: Error { case malformed(String) }

    static func readMono16kSamples(at url: URL) throws -> [Float] {
        let data = try Data(contentsOf: url)
        guard data.count >= 44, data[data.startIndex ..< data.startIndex + 4] == Data("RIFF".utf8),
              data[data.startIndex + 8 ..< data.startIndex + 12] == Data("WAVE".utf8)
        else { throw ReaderError.malformed("not a RIFF/WAVE file: \(url.lastPathComponent)") }

        var offset = data.startIndex + 12
        var samples: [Float]?
        while offset + 8 <= data.endIndex {
            guard let chunkID = String(bytes: data[offset ..< offset + 4], encoding: .ascii) else {
                throw ReaderError.malformed("unreadable chunk header")
            }
            let chunkLength = Int(readLE32(data, at: offset + 4))
            let bodyStart = offset + 8
            guard chunkLength >= 0, bodyStart + chunkLength <= data.endIndex else {
                throw ReaderError.malformed("truncated chunk \(chunkID)")
            }
            if chunkID == "data" {
                let body = data[bodyStart ..< bodyStart + chunkLength]
                var values = [Float](repeating: 0, count: body.count / 2)
                body.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
                    for i in 0..<values.count {
                        let v = Int16(bitPattern:
                            UInt16(raw.loadUnaligned(fromByteOffset: i * 2, as: UInt16.self)))
                        values[i] = Float(v) / 32768.0
                    }
                }
                samples = values
                break
            }
            offset = bodyStart + chunkLength + (chunkLength & 1)
        }
        guard var values = samples else {
            throw ReaderError.malformed("no data chunk in \(url.lastPathComponent)")
        }
        // Guard against fixtures with odd trailing bytes.
        if values.count % 2 == 1 { values.removeLast() }
        return values
    }

    private static func readLE32(_ data: Data, at index: Data.Index) -> UInt32 {
        (UInt32(data[index])
         | (UInt32(data[index + 1]) << 8)
         | (UInt32(data[index + 2]) << 16)
         | (UInt32(data[index + 3]) << 24))
    }
}
