import XCTest
@testable import LiveTranslateIOS

/// Golden-fixture verification of `GigaAMLogMelExtractor`.
///
/// Fixtures (`LiveTranslateIOSTests/Fixtures/`) are generated by
/// `scripts/generate_coreml_golden_fixtures.py`: Russian speech synthesized
/// with the macOS `say` voice, features computed by the torchaudio pipeline
/// the Core ML conversion used (float32).
///
/// ## Error budget — why maxErr is asserted at 2e-3, not 1e-4
///
/// `scripts/analyze_golden_noise_floor.py` measured, against a numpy float64
/// recomputation of the same contract:
///
/// | comparison                       | max err   | mean err | entries > 1e-4 |
/// |----------------------------------|-----------|----------|----------------|
/// | torchaudio golden (f32) vs truth | 1.49e-3   | ~6e-6    | ~1 %           |
/// | Swift extractor       vs truth   | 1.39e-4   | ~2e-6    | 2 / 192 000    |
/// | Swift extractor vs golden (f32)  | 1.48e-3   | ~7e-6    | ~1 %           |
///
/// The Swift-vs-golden residual is the **golden's own float32 FFT noise**,
/// concentrated in low-energy high mel bins (worst at bin 63) where float32
/// rounding of the reference FFT is amplified by the logarithm. The Swift
/// pipeline computes in Double and is the more accurate of the two; matching
/// the reference's float32 bit-noise would require replicating pocketfft's
/// exact operation order, which is neither possible nor desirable.
///
/// A structural DSP bug (wrong window, wrong mel scale, wrong filterbank
/// formula, off-by-one framing) produces errors of 0.1–1.0+, three orders of
/// magnitude above these thresholds. The assertions below therefore check:
/// max ≤ 2e-3, mean ≤ 1e-5, ≤ 2 % of entries above 1e-4, an exact padding
/// tail, and the exact `length` input.
final class CoreMLLogMelGoldenTests: XCTestCase {
    private let floorValue = Float(GigaAMLogMelExtractor.logFloor)

    // MARK: - Golden fixtures

    func testGoldenFeatures() throws {
        for name in ["test_ru_short", "test_ru_long", "test_ru_35s"] {
            let fixture = try GoldenFixture.load(named: name)
            let extractor = try GigaAMLogMelExtractor()
            let features = try extractor.extract(samples: fixture.samples)

            XCTAssertEqual(features.frameCount, fixture.frames, "\(name): length input")

            let arr = features.multiArray
            XCTAssertEqual(arr.shape, [1, 64, 2999], "\(name): output shape")
            let melStride = arr.strides[1].intValue
            let frameStride = arr.strides[2].intValue
            let ptr = arr.dataPointer.bindMemory(to: Float.self, capacity: arr.count)

            var maxErr: Float = 0
            var errSum: Double = 0
            var overThreshold = 0
            for m in 0..<GigaAMLogMelExtractor.nMels {
                for f in 0..<fixture.computedFrames {
                    let swift = ptr[m * melStride + f * frameStride]
                    let golden = fixture.golden[m * fixture.computedFrames + f]
                    let err = abs(swift - golden)
                    maxErr = max(maxErr, err)
                    errSum += Double(err)
                    if err > 1e-4 { overThreshold += 1 }
                }
            }
            let meanErr = errSum / Double(64 * fixture.computedFrames)
            let overRatio = Double(overThreshold) / Double(64 * fixture.computedFrames)

            XCTAssertLessThanOrEqual(
                maxErr, 2e-3,
                "\(name): max err \(maxErr) — see header of CoreMLLogMelGoldenTests"
            )
            XCTAssertLessThanOrEqual(meanErr, 1e-5, "\(name): mean err \(meanErr)")
            XCTAssertLessThanOrEqual(overRatio, 0.02, "\(name): \(overThreshold) entries > 1e-4")

            // Padding columns past the audio are exactly log(1e-9) —
            // zero-padded reference audio clamps at the floor.
            for m in 0..<GigaAMLogMelExtractor.nMels {
                for f in fixture.computedFrames..<GigaAMLogMelExtractor.maxFrames {
                    XCTAssertEqual(
                        ptr[m * melStride + f * frameStride], floorValue,
                        "\(name): padding at mel \(m) frame \(f)"
                    )
                }
            }
        }
    }

    /// The extractor reuses one persistent output array — the second call
    /// must fully overwrite the first (no stale columns from longer audio).
    func testConsecutiveExtractsDoNotLeakState() throws {
        let long = try GoldenFixture.load(named: "test_ru_long")
        let short = try GoldenFixture.load(named: "test_ru_short")
        let extractor = try GigaAMLogMelExtractor()

        _ = try extractor.extract(samples: long.samples)
        let second = try extractor.extract(samples: short.samples)

        XCTAssertEqual(second.frameCount, short.frames)
        let arr = second.multiArray
        let melStride = arr.strides[1].intValue
        let frameStride = arr.strides[2].intValue
        let ptr = arr.dataPointer.bindMemory(to: Float.self, capacity: arr.count)
        for m in 0..<GigaAMLogMelExtractor.nMels {
            for f in short.computedFrames..<GigaAMLogMelExtractor.maxFrames {
                XCTAssertEqual(
                    ptr[m * melStride + f * frameStride], floorValue,
                    "stale column leaked from previous extract at mel \(m) frame \(f)"
                )
            }
        }
    }

    // MARK: - Framing formulas

    func testFrameCountFormula() {
        typealias E = GigaAMLogMelExtractor
        // (n - 320) / 160 + 1, floored; anything shorter than the window
        // still reports one frame (the zero-padded reference behavior).
        XCTAssertEqual(E.frameCount(sampleCount: 0), 1)
        XCTAssertEqual(E.frameCount(sampleCount: 1), 1)
        XCTAssertEqual(E.frameCount(sampleCount: 319), 1)
        XCTAssertEqual(E.frameCount(sampleCount: 320), 1)
        XCTAssertEqual(E.frameCount(sampleCount: 321), 1)
        XCTAssertEqual(E.frameCount(sampleCount: 480), 2)
        XCTAssertEqual(E.frameCount(sampleCount: 480_000), 2999)
        // Known fixture values (see *.meta.json).
        XCTAssertEqual(E.frameCount(sampleCount: 46_068), 286)
        XCTAssertEqual(E.frameCount(sampleCount: 314_033), 1961)
    }

    func testComputedFrameCountFormula() {
        typealias E = GigaAMLogMelExtractor
        // Frames overlapping real audio: ceil(n / hop), capped at 2999.
        XCTAssertEqual(E.computedFrameCount(sampleCount: 0), 0)
        XCTAssertEqual(E.computedFrameCount(sampleCount: 1), 1)
        XCTAssertEqual(E.computedFrameCount(sampleCount: 160), 1)
        XCTAssertEqual(E.computedFrameCount(sampleCount: 161), 2)
        XCTAssertEqual(E.computedFrameCount(sampleCount: 320), 2)
        // Known fixture values — the 1–2 boundary frames past `frameCount`.
        XCTAssertEqual(E.computedFrameCount(sampleCount: 46_068), 288)
        XCTAssertEqual(E.computedFrameCount(sampleCount: 314_033), 1963)
        XCTAssertEqual(E.computedFrameCount(sampleCount: 480_000), 2999)
    }

    // MARK: - Degenerate and out-of-contract inputs

    /// Digital silence clamps everywhere — every column, computed or padded,
    /// is exactly log(1e-9), and the length input is 1.
    func testSilenceIsAllFloor() throws {
        let extractor = try GigaAMLogMelExtractor()
        let features = try extractor.extract(samples: [Float](repeating: 0, count: 16_000))
        XCTAssertEqual(features.frameCount, 99)

        let arr = features.multiArray
        let melStride = arr.strides[1].intValue
        let frameStride = arr.strides[2].intValue
        let ptr = arr.dataPointer.bindMemory(to: Float.self, capacity: arr.count)
        for m in 0..<GigaAMLogMelExtractor.nMels {
            for f in 0..<GigaAMLogMelExtractor.maxFrames {
                XCTAssertEqual(ptr[m * melStride + f * frameStride], floorValue)
            }
        }
    }

    func testSineEnergyLandsInExpectedMelBand() throws {
        let extractor = try GigaAMLogMelExtractor()
        // 1 kHz sine at full scale, 0.5 s.
        let n = 8_000
        var samples = [Float](repeating: 0, count: n)
        for i in 0..<n {
            samples[i] = sin(2.0 * Float.pi * 1000.0 * Float(i) / 16_000.0)
        }
        let features = try extractor.extract(samples: samples)
        let arr = features.multiArray
        let melStride = arr.strides[1].intValue
        let frameStride = arr.strides[2].intValue
        let ptr = arr.dataPointer.bindMemory(to: Float.self, capacity: arr.count)

        let frame = 40
        var bestMel = 0
        var bestValue = -Float.infinity
        for m in 0..<GigaAMLogMelExtractor.nMels {
            let v = ptr[m * melStride + frame * frameStride]
            if v > bestValue { bestValue = v; bestMel = m }
        }
        // hzToMel(1000) ≈ 1000; the 1 kHz line lands around mel bin 23 of 64
        // (bin width ≈ 43.7 mel ≈ 43.7 Hz there).
        XCTAssertTrue((18..<29).contains(bestMel), "1 kHz energy peaked at mel bin \(bestMel)")
        // The line must dominate the top of the band by a wide margin.
        XCTAssertGreaterThan(bestValue - ptr[63 * melStride + frame * frameStride], 5.0)
    }

    func testTooLongThrows() throws {
        let extractor = try GigaAMLogMelExtractor()
        let oversized = [Float](repeating: 0, count: GigaAMLogMelExtractor.maxSamples + 1)
        XCTAssertThrowsError(try extractor.extract(samples: oversized)) { error in
            guard case GigaAMLogMelExtractor.ExtractorError.tooLong = error else {
                return XCTFail("expected tooLong, got \(error)")
            }
        }
    }
}

// MARK: - Fixture loading

private struct GoldenFixture {
    let samples: [Float]
    let golden: [Float]      // [64, computedFrames] row-major
    let frames: Int
    let computedFrames: Int

    struct Meta: Decodable {
        let wav: String
        let featuresFile: String?
        let frames: Int
        let computedFrames: Int
    }

    /// Locates a fixture resource whether xcodegen flattened it into the
    /// bundle root or kept it under a `Fixtures/` subdirectory.
    static func resourceURL(name: String, ext: String) throws -> URL {
        let bundle = Bundle(for: CoreMLLogMelGoldenTests.self)
        if let url = bundle.url(forResource: name, withExtension: ext, subdirectory: "Fixtures") {
            return url
        }
        guard let url = bundle.url(forResource: name, withExtension: ext) else {
            throw XCTSkip("fixture \(name).\(ext) not bundled — ensure the Fixtures " +
                          "directory is part of the LiveTranslateIOSTests resources")
        }
        return url
    }

    static func load(named name: String) throws -> GoldenFixture {
        let metaURL = try resourceURL(name: name, ext: "meta.json")
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let meta = try decoder.decode(Meta.self, from: Data(contentsOf: metaURL))
        // `meta.wav` is authoritative: the >30 s fixture's golden features
        // were computed against its window-truncated twin, not the original.
        let wavName = (meta.wav as NSString).deletingPathExtension
        let wavURL = try resourceURL(name: wavName, ext: "wav")
        let samples = try TestWAVReader.readMono16kSamples(at: wavURL)
        let goldenFile = meta.featuresFile ?? "\(name).logmel.f32"
        let goldenURL = try resourceURL(
            name: (goldenFile as NSString).deletingPathExtension, ext: "f32")
        let goldenData = try Data(contentsOf: goldenURL)
        let golden = goldenData.withUnsafeBytes { raw in
            Array(raw.bindMemory(to: Float.self))
        }
        return GoldenFixture(
            samples: samples, golden: golden,
            frames: meta.frames, computedFrames: meta.computedFrames
        )
    }
}

/// Minimal RIFF/WAV reader for the fixture format (16-bit PCM, mono, 16 kHz).
/// Test-support only — the app's audio stack uses AVAudioEngine.
enum TestWAVReader {
    enum ReaderError: Error { case malformed(String) }

    static func readMono16kSamples(at url: URL) throws -> [Float] {
        let data = try Data(contentsOf: url)
        guard data.count >= 44, data[data.startIndex ..< data.startIndex + 4] == Data("RIFF".utf8),
              data[data.startIndex + 8 ..< data.startIndex + 12] == Data("WAVE".utf8)
        else { throw ReaderError.malformed("not a RIFF/WAVE file: \(url.lastPathComponent)") }

        var offset = data.startIndex + 12
        var samples: [Float]?
        while offset + 8 <= data.endIndex {
            guard let chunkID = String(bytes: data[offset ..< offset + 4], encoding: .ascii) else {
                throw ReaderError.malformed("unreadable chunk header")
            }
            let b = [UInt8](data[offset + 4 ..< offset + 8])
            // WAV is little-endian.
            let chunkSize = Int(b[0]) | Int(b[1]) << 8 | Int(b[2]) << 16 | Int(b[3]) << 24

            if chunkID == "data" {
                let start = offset + 8
                let end = min(start + chunkSize, data.endIndex)
                var out = [Float]()
                out.reserveCapacity((end - start) / 2)
                var i = start
                while i + 1 < end {
                    let lo = UInt16(data[i])
                    let hi = UInt16(data[i + 1])
                    out.append(Float(Int16(bitPattern: lo | (hi << 8))) / 32768.0)
                    i += 2
                }
                samples = out
                break
            }
            offset += 8 + chunkSize + (chunkSize % 2)
        }
        guard let result = samples else {
            throw ReaderError.malformed("no data chunk: \(url.lastPathComponent)")
        }
        return result
    }
}
