import Foundation
import Accelerate
import CoreML

/// Exact re-implementation of the GigaAM-v3 feature extraction contract.
///
/// Must stay bit-faithful to the torchaudio reference used for the Core ML
/// conversion (verified against golden fixtures generated by
/// `scripts/generate_coreml_golden_fixtures.py`):
///
/// ```
/// MelSpectrogram(sample_rate: 16000, n_mels: 64, win_length: 320,
///                hop_length: 160, n_fft: 320, center: false,
///                mel_scale: "htk", norm: nil)
/// features = mel(audio_padded_to_30s).clamp(1e-9, 1e9).log()
/// frames   = (nSamples - 320) / 160 + 1
/// ```
///
/// Forbidden deviations (would desync the encoder): n_fft 512, 80 mels,
/// Slaney mel scale, center=true, mean/variance normalization.
///
/// NOT thread-safe by design: owned and called exclusively from inside the
/// engine actor.
final class GigaAMLogMelExtractor {
    // MARK: Contract constants — do not tune.

    static let sampleRate = 16_000
    static let nFFT = 320
    static let winLength = 320
    static let hopLength = 160
    static let nMels = 64
    static let nFreqBins = nFFT / 2 + 1   // 161
    /// 30 s window: the encoder's fixed input width.
    static let maxSamples = 30 * sampleRate  // 480_000
    static let maxFrames = (maxSamples - winLength) / hopLength + 1  // 2999
    /// `log(clamp(0, 1e-9, 1e9))` — the value every padding frame carries.
    static let logFloor: Double = log(1e-9)
    static let clampMin = 1e-9
    static let clampMax = 1e9

    /// Frame count for the encoder `length` input (PyTorch `out_len`).
    /// Sub-window audio still reports one frame, mirroring the reference's
    /// zero-padded signal.
    static func frameCount(sampleCount: Int) -> Int {
        precondition(sampleCount >= 0)
        if sampleCount < winLength { return 1 }
        return (sampleCount - winLength) / hopLength + 1
    }

    /// Frames of the padded 30 s window that overlap real audio.
    ///
    /// Frame f covers [f·hop, f·hop + win) and carries signal whenever
    /// f·hop < n. The reference computes mel over the FULL zero-padded
    /// window, so the 1–2 boundary frames past `frameCount` hold real
    /// content — they must be computed even though the encoder masks at
    /// `length`. Columns beyond this count are the constant log(1e-9).
    static func computedFrameCount(sampleCount: Int) -> Int {
        precondition(sampleCount >= 0)
        return min(maxFrames, (sampleCount + hopLength - 1) / hopLength)
    }

    // MARK: Cached, immutable DSP state.

    /// Periodic Hann: `0.5 * (1 - cos(2πn/N))`, N = 320
    /// (torch.hann_window(320, periodic: true)).
    private let hannWindow: [Double]
    /// DFT basis matrices, row-major [nFreqBins × nFFT], Double precision
    /// so our error stays below torchaudio's own float32 FFT error.
    private let dftReal: [Double]   // cos(2πkn/N)
    private let dftImag: [Double]   // -sin(2πkn/N)
    /// HTK mel filterbank, row-major [nMels × nFreqBins], norm = none.
    private let melFilterbank: [Double]

    // MARK: Reusable work buffers (sized for maxFrames).

    private var framesMatrix: [Double]    // [nFFT × maxFrames]
    private var spectrumReal: [Double]    // [nFreqBins × maxFrames]
    private var spectrumImag: [Double]    // [nFreqBins × maxFrames]
    private var powerSpectrum: [Double]   // [nFreqBins × maxFrames]
    private var melOut: [Double]          // [nMels × maxFrames]
    /// Persistent encoder input array — the whole point of the reuse.
    private let outputArray: MLMultiArray

    enum ExtractorError: Error, CustomStringConvertible {
        case tooLong(samples: Int)

        var description: String {
            switch self {
            case .tooLong(let samples):
                return "Audio exceeds the 30 s Core ML window (\(samples) > \(GigaAMLogMelExtractor.maxSamples) samples); the VAD layer must split it upstream."
            }
        }
    }

    init() throws {
        var hann = [Double](repeating: 0, count: Self.nFFT)
        let twoPiOverN = 2.0 * Double.pi / Double(Self.nFFT)
        for n in 0..<Self.nFFT {
            hann[n] = 0.5 * (1.0 - cos(Double(n) * twoPiOverN))
        }
        self.hannWindow = hann

        var re = [Double](repeating: 0, count: Self.nFreqBins * Self.nFFT)
        var im = [Double](repeating: 0, count: Self.nFreqBins * Self.nFFT)
        for k in 0..<Self.nFreqBins {
            for n in 0..<Self.nFFT {
                let angle = twoPiOverN * Double(k) * Double(n)
                re[k * Self.nFFT + n] = cos(angle)
                im[k * Self.nFFT + n] = -sin(angle)
            }
        }
        self.dftReal = re
        self.dftImag = im
        self.melFilterbank = Self.buildHTKMelFilterbank()

        let workRows = Self.nFFT * Self.maxFrames
        let specRows = Self.nFreqBins * Self.maxFrames
        let melRows = Self.nMels * Self.maxFrames
        self.framesMatrix = [Double](repeating: 0, count: workRows)
        self.spectrumReal = [Double](repeating: 0, count: specRows)
        self.spectrumImag = [Double](repeating: 0, count: specRows)
        self.powerSpectrum = [Double](repeating: 0, count: specRows)
        self.melOut = [Double](repeating: 0, count: melRows)

        self.outputArray = try MLMultiArray(
            shape: [1, NSNumber(value: Self.nMels), NSNumber(value: Self.maxFrames)],
            dataType: .float32
        )
    }

    /// HTK mel filterbank, mirroring `torchaudio.functional.melscale_fbanks`
    /// with `mel_scale="htk"`, `f_min=0`, `f_max=8000`, `norm=nil`:
    /// mel(f) = 2595·log10(1 + f/700), 66 mel-spaced points, triangular
    /// overlap on the 161 FFT bins (bin frequency = 50 Hz × k).
    private static func buildHTKMelFilterbank() -> [Double] {
        func hzToMel(_ f: Double) -> Double { 2595.0 * log10(1.0 + f / 700.0) }
        func melToHz(_ m: Double) -> Double { 700.0 * (pow(10.0, m / 2595.0) - 1.0) }

        let fMin = 0.0
        let fMax = Double(sampleRate) / 2.0  // 8000 Hz

        var melPoints = [Double](repeating: 0, count: nMels + 2)
        let mMin = hzToMel(fMin)
        let mMax = hzToMel(fMax)
        for i in 0..<(nMels + 2) {
            melPoints[i] = mMin + (mMax - mMin) * Double(i) / Double(nMels + 1)
        }
        let hzPoints = melPoints.map(melToHz)

        var fb = [Double](repeating: 0, count: nMels * nFreqBins)
        for m in 0..<nMels {
            let fPrev = hzPoints[m]
            let fCur = hzPoints[m + 1]
            let fNext = hzPoints[m + 2]
            for k in 0..<nFreqBins {
                let binFreq = Double(k) * Double(sampleRate) / Double(nFFT)
                let rise = (binFreq - fPrev) / (fCur - fPrev)
                let fall = (fNext - binFreq) / (fNext - fCur)
                // True triangle (torchaudio `min(down, up)` semantics) —
                // NOT rise·fall, which bends the filter shape.
                let value = min(rise, fall)
                fb[m * nFreqBins + k] = value > 0 ? value : 0
            }
        }
        return fb
    }

    // MARK: Extraction

    /// The persistent [1, 64, 2999] output array — exposed so the engine can
    /// build one reusable prediction-input provider around it.
    var outputFeatures: MLMultiArray { outputArray }

    struct Features {
        /// [1, 64, 2999] Float32, encoder input. Columns ≥ `frameCount`
        /// carry `log(1e-9)` exactly like zero-padded reference audio.
        /// The array is owned by the extractor and reused across calls —
        /// consume it (or copy it) before the next `extract`.
        let multiArray: MLMultiArray
        /// Real (unpadded) frame count for the `length` input.
        let frameCount: Int
    }

    /// Extract log-mel features for one segment.
    /// - Throws: `ExtractorError.tooLong` if samples exceed the 30 s window.
    func extract(samples: [Float]) throws -> Features {
        guard samples.count <= Self.maxSamples else {
            throw ExtractorError.tooLong(samples: samples.count)
        }
        // Compute every frame that overlaps real audio (boundary frames
        // included); the rest of the window is the constant log floor.
        let frames = Self.computedFrameCount(sampleCount: samples.count)

        // 1. Windowed frames: framesMatrix[n, f] = x[f*hop + n] * hann[n].
        for f in 0..<frames {
            let base = f * Self.hopLength
            for n in 0..<Self.nFFT {
                let idx = base + n
                let x: Double = idx < samples.count ? Double(samples[idx]) : 0.0
                framesMatrix[n * Self.maxFrames + f] = x * hannWindow[n]
            }
        }

        // 2. Power spectrum via DFT matrices. Results row-major
        //    [nFreqBins × maxFrames], linear index k * maxFrames + f.
        let m = Int32(Self.maxFrames)
        cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                    Int32(Self.nFreqBins), m, Int32(Self.nFFT),
                    1.0, dftReal, Int32(Self.nFFT),
                    framesMatrix, m,
                    0.0, &spectrumReal, m)
        cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                    Int32(Self.nFreqBins), m, Int32(Self.nFFT),
                    1.0, dftImag, Int32(Self.nFFT),
                    framesMatrix, m,
                    0.0, &spectrumImag, m)
        for i in 0..<(Self.nFreqBins * Self.maxFrames) {
            powerSpectrum[i] = spectrumReal[i] * spectrumReal[i]
                + spectrumImag[i] * spectrumImag[i]
        }

        // 3. Mel projection.
        cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                    Int32(Self.nMels), m, Int32(Self.nFreqBins),
                    1.0, melFilterbank, Int32(Self.nFreqBins),
                    powerSpectrum, m,
                    0.0, &melOut, m)

        // 4. Clamp + log into the persistent output array, honoring the
        //    array's actual strides (do not assume contiguity).
        let outCount = outputArray.count
        let outPtr = outputArray.dataPointer.bindMemory(
            to: Float.self, capacity: outCount
        )
        let melStride = outputArray.strides[1].intValue
        let frameStride = outputArray.strides[2].intValue
        for mIdx in 0..<Self.nMels {
            let melRow = mIdx * Self.maxFrames
            let outRow = mIdx * melStride
            for f in 0..<frames {
                var v = melOut[melRow + f]
                if v < Self.clampMin { v = Self.clampMin }
                if v > Self.clampMax { v = Self.clampMax }
                outPtr[outRow + f * frameStride] = Float(log(v))
            }
            // Padding columns carry log(1e-9), matching zero-padded audio
            // run through the reference pipeline.
            let floor32 = Float(Self.logFloor)
            for f in frames..<Self.maxFrames {
                outPtr[outRow + f * frameStride] = floor32
            }
        }

        return Features(
            multiArray: outputArray,
            frameCount: Self.frameCount(sampleCount: samples.count)
        )
    }
}
